export const FOOD_GRADES = [
  {
    id: "common",
    name: "일반",
    probability: 55,
    expRange: [5, 10],
    moneyRange: [10, 30],
    tone: "common",
    foods: ["해바라기씨", "당근 조각", "옥수수 한 알"],
  },
  {
    id: "uncommon",
    name: "고급",
    probability: 28,
    expRange: [15, 25],
    moneyRange: [40, 80],
    tone: "uncommon",
    foods: ["말린 사과", "고구마칩", "귀리볼"],
  },
  {
    id: "rare",
    name: "희귀",
    probability: 12,
    expRange: [40, 70],
    moneyRange: [150, 300],
    tone: "rare",
    foods: ["치즈큐브", "딸기조각", "견과믹스"],
  },
  {
    id: "epic",
    name: "영웅",
    probability: 4,
    expRange: [120, 200],
    moneyRange: [700, 1200],
    tone: "epic",
    foods: ["황금 해바라기씨", "꿀코팅 견과", "프리미엄 치즈볼"],
  },
  {
    id: "legendary",
    name: "전설",
    probability: 0.9,
    expRange: [500, 800],
    moneyRange: [4000, 7000],
    tone: "legendary",
    foods: ["무지개 치즈", "별빛 곡물"],
  },
  {
    id: "mythic",
    name: "신화",
    probability: 0.1,
    expRange: [2000, 3500],
    moneyRange: [30000, 50000],
    tone: "mythic",
    foods: ["우주 해바라기씨", "햄스터 신의 간식"],
  },
];

export const HAMSTER_TIERS = [
  {
    minLevel: 1,
    name: "아기 햄스터",
    moneyMultiplier: 1,
    expMultiplier: 1,
    upgradeCostMultiplier: 1,
  },
  {
    minLevel: 5,
    name: "통통 햄스터",
    moneyMultiplier: 1.15,
    expMultiplier: 1.05,
    upgradeCostMultiplier: 1.8,
  },
  {
    minLevel: 15,
    name: "볼주머니 햄스터",
    moneyMultiplier: 1.35,
    expMultiplier: 1.1,
    upgradeCostMultiplier: 3.2,
  },
  {
    minLevel: 30,
    name: "치즈 햄스터",
    moneyMultiplier: 1.7,
    expMultiplier: 1.2,
    upgradeCostMultiplier: 5.5,
  },
  {
    minLevel: 50,
    name: "황금 햄스터",
    moneyMultiplier: 2.2,
    expMultiplier: 1.35,
    upgradeCostMultiplier: 9,
  },
  {
    minLevel: 80,
    name: "전설 햄스터",
    moneyMultiplier: 3,
    expMultiplier: 1.5,
    upgradeCostMultiplier: 15,
  },
  {
    minLevel: 120,
    name: "신화 햄스터",
    moneyMultiplier: 4.5,
    expMultiplier: 1.8,
    upgradeCostMultiplier: 25,
  },
];

export const UPGRADE_MULTIPLIER_ANCHORS = [
  [0, 1],
  [1, 1.08],
  [2, 1.16],
  [3, 1.25],
  [4, 1.35],
  [5, 1.5],
  [6, 1.68],
  [7, 1.88],
  [8, 2.1],
  [9, 2.35],
  [10, 2.65],
  [15, 4.5],
  [20, 8],
  [25, 14],
  [30, 25],
];

export const DEFAULT_STATE = {
  version: 1,
  money: 0,
  hamster: {
    level: 1,
    exp: 0,
    upgrade: 0,
  },
  collection: {},
  rareHistory: [],
  logs: ["새 햄스터가 입주했습니다. 아직 아무것도 모르지만 당당합니다."],
  stats: {
    totalDraws: 0,
    totalEarnedMoney: 0,
    totalEarnedExp: 0,
    maxMoneyBurst: 0,
  },
  rankingSeed: {
    bestLevel: 1,
    bestUpgrade: 0,
    totalEarnedMoney: 0,
    updatedAt: null,
  },
};
